# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Admin
  admin_email: admin@yopmail.com
  admin_password: 123456abc
  domain_name: example.com
  secret_key_base: fec1806e6ac978f142f56e2f6d45c46bebae59ff42b2e7854aa3e29bf066490f4dfe04249513d5092ac5b69e85a9f29be170874f6eb1ae9e6f6503d9ee9dd1e2

test:
  domain_name: example.com 
  secret_key_base: 3002a646c6ef14ae9772dfe15c3f94fca3cd1d00f639295954f77d5aeef00f8a00514e61f3d454915cc0ec57603c5193528797eab7aba181d282612c7c3ce7cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
